package ExtendedRoboRoute.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

@Generated
public class QueriesGenerated {
  public static Object propertyMacro_GetPropertyValue_2397178398406548033(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(SNodeOperations.cast(_context.getNode(), MetaAdapterFactory.getConcept(0x5932703a14ff46bdL, 0xa9cfc081255d1355L, 0x21447d0d744753d8L, "ExtendedRoboRoute.structure.ForwardWithVariables")), MetaAdapterFactory.getReferenceLink(0x5932703a14ff46bdL, 0xa9cfc081255d1355L, 0x21447d0d744753d8L, 0x21447d0d744b8b2aL, "length")), MetaAdapterFactory.getProperty(0x5932703a14ff46bdL, 0xa9cfc081255d1355L, 0x21447d0d7447cdafL, 0x21447d0d7447ce30L, "value"));
  }
}
