package RoboRoute.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private final ConceptPresentation props_Boundary = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Canvas = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Command = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Forward = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Shape = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_StartPoint = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Turn = new ConceptPresentationBuilder().create();

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case 0:
        return props_Boundary;
      case 1:
        return props_Canvas;
      case 2:
        return props_Command;
      case 3:
        return props_Forward;
      case 4:
        return props_Shape;
      case 5:
        return props_StartPoint;
      case 6:
        return props_Turn;
    }
    throw new IllegalStateException("Unknown concept " + c);
  }
}
