package RoboRoute.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum ETurn {
  RIGHT("RIGHT", 0),
  LEFT("LEFT", 1),
  UP("UP", 2),
  DOWN("DOWN", 3);

  private final String myName;
  public String getName() {
    return myName;
  }
  private final int myValue;
  ETurn(String name, int value) {
    myName = name;
    myValue = value;
  }
  public int getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return Integer.toString(myValue);
  }
  public static List<ETurn> getConstants() {
    List<ETurn> list = ListSequence.fromList(new LinkedList<ETurn>());
    ListSequence.fromList(list).addElement(ETurn.RIGHT);
    ListSequence.fromList(list).addElement(ETurn.LEFT);
    ListSequence.fromList(list).addElement(ETurn.UP);
    ListSequence.fromList(list).addElement(ETurn.DOWN);
    return list;
  }
  public static ETurn getDefault() {
    return ETurn.RIGHT;
  }
  public static ETurn parseValue(String value) {
    if (value == null) {
      return ETurn.getDefault();
    }
    if (value.equals(ETurn.RIGHT.getValueAsString())) {
      return ETurn.RIGHT;
    }
    if (value.equals(ETurn.LEFT.getValueAsString())) {
      return ETurn.LEFT;
    }
    if (value.equals(ETurn.UP.getValueAsString())) {
      return ETurn.UP;
    }
    if (value.equals(ETurn.DOWN.getValueAsString())) {
      return ETurn.DOWN;
    }
    return ETurn.getDefault();
  }
}
