package RoboRoute.sandbox;

/*Generated by MPS */

import javax.swing.JFrame;
import javax.swing.JPanel;
import java.awt.Graphics;
import java.awt.Point;
import java.awt.Dimension;

public class MyRoboRoute extends JFrame {
  private JPanel panel = new JPanel() {
    @Override
    protected void paintComponent(Graphics graphics) {
      super.paintComponent(graphics);
      Point currentStartPoint = new Point(62, 62);
      int direction = 0;

      graphics.drawRect(50, 50, 500, 600);
      graphics.drawOval(60, 60, 4, 4);
      direction = changeDirection(0);
      currentStartPoint = moveForward(currentStartPoint, direction, 200, graphics);
      direction = changeDirection(0);
      direction = changeDirection(3);
      currentStartPoint = moveForward(currentStartPoint, direction, 200, graphics);
      direction = changeDirection(1);
      currentStartPoint = moveForward(currentStartPoint, direction, 50, graphics);
      direction = changeDirection(3);
      currentStartPoint = moveForward(currentStartPoint, direction, 90, graphics);
      direction = changeDirection(0);
      currentStartPoint = moveForward(currentStartPoint, direction, 100, graphics);
    }
  };

  public Point moveForward(Point currPoint, int currDirection, int distance, Graphics graphics) {
    Point resPoint = new Point();
    // move right 
    if (currDirection == 0) {
      resPoint.x = currPoint.x + distance;
      resPoint.y = currPoint.y;
    }
    // move left 
    if (currDirection == 1) {
      resPoint.x = currPoint.x - distance;
      resPoint.y = currPoint.y;
    }
    // move up 
    if (currDirection == 2) {
      resPoint.x = currPoint.x;
      resPoint.y = currPoint.y - distance;
    }
    // move down 
    if (currDirection == 3) {
      resPoint.x = currPoint.x;
      resPoint.y = currPoint.y + distance;
    }
    // TODO 
    graphics.drawLine(currPoint.x, currPoint.y, resPoint.x, resPoint.y);
    return resPoint;
  }

  public int changeDirection(int turn) {
    return turn;
  }

  public static void main(String[] args) {
    MyRoboRoute canvas = new MyRoboRoute();
    canvas.initialize();
  }

  public void executeCommands() {
  }

  public void initialize() {
    this.setTitle("MyRoboRoute");
    this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    this.add(panel);
    panel.setPreferredSize(new Dimension(1000, 1000));
    this.pack();
    this.setVisible(true);
  }
}
