package RoboRoute.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.DefaultNodeEditor;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.openapi.editor.EditorContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.nodeEditor.cells.EditorCell_Constant;
import jetbrains.mps.nodeEditor.cellProviders.CellProviderWithRole;
import jetbrains.mps.lang.editor.cellProviders.PropertyCellProvider;
import jetbrains.mps.nodeEditor.EditorManager;

public class Boundary_Editor extends DefaultNodeEditor {
  public EditorCell createEditorCell(EditorContext editorContext, SNode node) {
    return this.createCollection_daxp5d_a(editorContext, node);
  }
  private EditorCell createCollection_daxp5d_a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createIndent2(editorContext, node);
    editorCell.setCellId("Collection_daxp5d_a");
    editorCell.setBig(true);
    editorCell.addEditorCell(this.createConstant_daxp5d_a0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_daxp5d_b0(editorContext, node));
    editorCell.addEditorCell(this.createProperty_daxp5d_c0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_daxp5d_d0(editorContext, node));
    editorCell.addEditorCell(this.createProperty_daxp5d_e0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_daxp5d_f0(editorContext, node));
    editorCell.addEditorCell(this.createProperty_daxp5d_g0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_daxp5d_h0(editorContext, node));
    editorCell.addEditorCell(this.createProperty_daxp5d_i0(editorContext, node));
    return editorCell;
  }
  private EditorCell createConstant_daxp5d_a0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "Your route is inside boundary");
    editorCell.setCellId("Constant_daxp5d_a0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createConstant_daxp5d_b0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "x:");
    editorCell.setCellId("Constant_daxp5d_b0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createProperty_daxp5d_c0(EditorContext editorContext, SNode node) {
    CellProviderWithRole provider = new PropertyCellProvider(node, editorContext);
    provider.setRole("upperLeftX");
    provider.setNoTargetText("<no upperLeftX>");
    EditorCell editorCell;
    editorCell = provider.createEditorCell(editorContext);
    editorCell.setCellId("property_upperLeftX");
    editorCell.setSubstituteInfo(provider.createDefaultSubstituteInfo());
    SNode attributeConcept = provider.getRoleAttribute();
    if (attributeConcept != null) {
      EditorManager manager = EditorManager.getInstanceFromContext(editorContext);
      return manager.createNodeRoleAttributeCell(attributeConcept, provider.getRoleAttributeKind(), editorCell);
    } else
    return editorCell;
  }
  private EditorCell createConstant_daxp5d_d0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "y:");
    editorCell.setCellId("Constant_daxp5d_d0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createProperty_daxp5d_e0(EditorContext editorContext, SNode node) {
    CellProviderWithRole provider = new PropertyCellProvider(node, editorContext);
    provider.setRole("upperLeftY");
    provider.setNoTargetText("<no upperLeftY>");
    EditorCell editorCell;
    editorCell = provider.createEditorCell(editorContext);
    editorCell.setCellId("property_upperLeftY");
    editorCell.setSubstituteInfo(provider.createDefaultSubstituteInfo());
    SNode attributeConcept = provider.getRoleAttribute();
    if (attributeConcept != null) {
      EditorManager manager = EditorManager.getInstanceFromContext(editorContext);
      return manager.createNodeRoleAttributeCell(attributeConcept, provider.getRoleAttributeKind(), editorCell);
    } else
    return editorCell;
  }
  private EditorCell createConstant_daxp5d_f0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "sizeX:");
    editorCell.setCellId("Constant_daxp5d_f0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createProperty_daxp5d_g0(EditorContext editorContext, SNode node) {
    CellProviderWithRole provider = new PropertyCellProvider(node, editorContext);
    provider.setRole("sizeX");
    provider.setNoTargetText("<no sizeX>");
    EditorCell editorCell;
    editorCell = provider.createEditorCell(editorContext);
    editorCell.setCellId("property_sizeX");
    editorCell.setSubstituteInfo(provider.createDefaultSubstituteInfo());
    SNode attributeConcept = provider.getRoleAttribute();
    if (attributeConcept != null) {
      EditorManager manager = EditorManager.getInstanceFromContext(editorContext);
      return manager.createNodeRoleAttributeCell(attributeConcept, provider.getRoleAttributeKind(), editorCell);
    } else
    return editorCell;
  }
  private EditorCell createConstant_daxp5d_h0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "sizeY:");
    editorCell.setCellId("Constant_daxp5d_h0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createProperty_daxp5d_i0(EditorContext editorContext, SNode node) {
    CellProviderWithRole provider = new PropertyCellProvider(node, editorContext);
    provider.setRole("sizeY");
    provider.setNoTargetText("<no sizeY>");
    EditorCell editorCell;
    editorCell = provider.createEditorCell(editorContext);
    editorCell.setCellId("property_sizeY");
    editorCell.setSubstituteInfo(provider.createDefaultSubstituteInfo());
    SNode attributeConcept = provider.getRoleAttribute();
    if (attributeConcept != null) {
      EditorManager manager = EditorManager.getInstanceFromContext(editorContext);
      return manager.createNodeRoleAttributeCell(attributeConcept, provider.getRoleAttributeKind(), editorCell);
    } else
    return editorCell;
  }
}
